version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ekonsilio
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ekonsilio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ekonsilio"]
      interval: 10s
      timeout: 5s
      retries: 5

  # backend:
  #   build:
  #     context: .
  #     dockerfile: apps/backend/Dockerfile
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://ekonsilio:password@localhost:5432/ekonsilio_db
  #   ports:
  #     - "3001:3001"

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: apps/admin/Dockerfile
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:3000"

  # visitor:
  #   build:
  #     context: .
  #     dockerfile: apps/visitor-chat/Dockerfile
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3002:3002"

volumes:
  postgres_data:
